---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    metallb.universe.tf/address-pool: homelab-services
    metallb.universe.tf/loadBalancerIPs: {{ .Values.gateway.loadBalancerIP }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "{{ .Values.gateway.hostname }}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "{{ .Values.gateway.hostname }}"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName }}
      allowedRoutes:
        namespaces:
          from: All
