---
- name: Read join command from local file
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ lookup('file', playbook_dir + '/../.join-token') }}"

- name: Check if node has already joined the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join the cluster
  ansible.builtin.command: "{{ kubeadm_join_command }}"
  when: not kubelet_conf.stat.exists
