---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bind9-tsig
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: bind9-tsig
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        tsig.key: |
          key "{{ .Values.bind9.tsigKeyName }}" {
            algorithm hmac-sha256;
            secret "{{ `{{ .secret }}` }}";
          };
        tsig-secret: "{{ `{{ .secret }}` }}"
  data:
    - secretKey: secret
      remoteRef:
        key: {{ .Values.bind9.tsigSecretOpRef.item }}/{{ .Values.bind9.tsigSecretOpRef.field }}
