apiVersion: v2
name: external-dns
description: external-dns instance using RFC2136 to write records to in-cluster BIND9
type: application
version: 0.1.0
dependencies:
  - name: external-dns
    version: 1.21.1
    repository: https://kubernetes-sigs.github.io/external-dns/
