apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Release.Name }}-db-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  length: 32
  symbols: 0
