apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: {{ .Release.Name }}-db-auth
    creationPolicy: Owner
    template:
      data:
        username: paperless
        password: "{{ `{{ .password }}` }}"
        # ngx envFrom convenience keys
        PAPERLESS_DBUSER: paperless
        PAPERLESS_DBPASS: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          kind: Password
          apiVersion: generators.external-secrets.io/v1alpha1
          name: {{ .Release.Name }}-db-password
