{{- if .Values.gpt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gpt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpt
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gpt
  ports:
    - name: http
      port: 8080
      targetPort: http
{{- end }}
