apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-superuser
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store | default "onepassword-sdk" }}
  target:
    name: {{ .Release.Name }}-superuser
    creationPolicy: Owner
    template:
      data:
        # ngx envFrom keys
        PAPERLESS_ADMIN_USER: "{{ `{{ .username }}` }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ `{{ .password }}` }}"
        PAPERLESS_ADMIN_MAIL: "{{ `{{ .email }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: paperless-superuser/username
    - secretKey: password
      remoteRef:
        key: paperless-superuser/password
    - secretKey: email
      remoteRef:
        key: paperless-superuser/email
