apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-valkey
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
