---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-es
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: truenas-iscsi-config
    creationPolicy: Owner
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: op://shimmer-labs/democratic-csi.driver-config-file.yaml/file
