---
apiVersion: v1
kind: Service
metadata:
  name: preview-smoke
  namespace: {{ .Values.previewSmoke.namespace }}
  labels:
    app: preview-smoke
spec:
  selector:
    app: preview-smoke
  ports:
    - port: 80
      targetPort: 80
