all:
  children:
    control_plane:
      hosts:
        k8s-cp-1:
          ansible_host: 10.22.6.100
    workers:
      hosts:
        k8s-w-1:
          ansible_host: 10.22.6.101
        k8s-w-2:
          ansible_host: 10.22.6.102
        k8s-w-3:
          ansible_host: 10.22.6.103
        k8s-w-4:
          ansible_host: 10.22.6.104
