---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bind9-tsig
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    name: bind9-tsig
    creationPolicy: Owner
  data:
    - secretKey: tsig-secret
      remoteRef:
        key: bind9-externaldns-tsig/secret
