k8s-gateway:
  domain: k8s.shimmerlabs.xyz
  ttl: 60
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.22.6.53"
  watchedResources:
    - HTTPRoute
    - Gateway
    - Ingress
    - Service
  fallthrough:
    enabled: false
