{{- if .Values.previewTunnel.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.previewTunnel.credentialsSecretName }}
spec:
  refreshInterval: 25h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.previewTunnel.externalSecret.store }}
  target:
    name: {{ .Values.previewTunnel.credentialsSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: {{ .Values.previewTunnel.externalSecret.remoteRef }}
{{- end }}
